using CustomizeMigrationTable.Migrations;
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Data.Entity.Migrations.Infrastructure;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CustomizeMigrationTable
{
    class Program
    {
        static void Main(string[] args)
        {
            // You can test the solution by running this console application as well
            // This will print the migration script just as if it were generated by Update-Database -Script
            var configuration = new Configuration();
            var migrator = new DbMigrator(configuration);

            var scriptor = new MigratorScriptingDecorator(migrator);
            string script = scriptor.ScriptUpdate(sourceMigration: null, targetMigration: null);

            Console.WriteLine(script);
            Console.ReadLine();
        }
    }
}
